language: node_js
node_js:
  - "4.2"
env:
  global:
    - ENV="CI"
    - SAUCE_USERNAME="oliverwoodings"
    - SAUCE_ACCESS_KEY="47807610-3129-4a60-95d7-5e5b62ead383"
cache:
  directories:
    - node_modules